finchcollector/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

#map out urls
urlpatterns = [
    #url endpoint, view to render, name of the route
    path('', views.home, name="home"),
    path('about/', views.about, name ='about'),
    path('finches/', views.finches_index, name = 'index'),
    path('finches/<int:finch_id>', views.finches_detail, name ="detail"),
    path('finches/create', views.FinchCreate.as_view(), name ="finches_create"),
    path('finches/<int:pk>/update', views.FinchUpdate.as_view(), name='finches_update'),
    path('finches/<int:pk>/delete', views.FinchDelete.as_view(), name='finches_delete'),
    path('finchess/<int:finch_id>/add_feeding', views.add_feeding, name='add_feeding'),
    path('toys/', views.ToyList.as_view(), name='toys_index'),
    path('toys/create/', views.ToyCreate.as_view(), name='toys_create'),
    path('toys/<int:pk>/update/', views.ToyUpdate.as_view(), name='toys_update'),
    path('toys/<int:pk>/delete/', views.ToyDelete.as_view(), name='toys_delete'),
    path('toys/<int:pk>/', views.ToyDetail.as_view(), name='toys_detail'),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date

MEALS = (
    # this is a tuple with multiple tuples
    # each of these is called a 2-tuple
    ('B', 'Breakfast'),
    ('L', 'Lunch'),
    ('D', 'Dinner'),
)
# Create your models here.
class Toy(models.Model):
    name = models.CharField(max_length=50)
    color = models.CharField(max_length=20)

    def __str__(self):
        return f'{self.color} {self.name}'

    def get_absolute_url(self):
        return reverse('toy_detail', kwargs={'pk': self.id})


class Finch(models.Model):
    name = models.CharField(max_length=150)
    color = models.CharField(max_length=150)
    description = models.TextField(max_length = 250)
    age = models.IntegerField()
    toys = models.ManyToManyField(Toy)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('detail', kwargs={'finch_id': self.id})
    

class Feeding(models.Model):
    # our model attributes go here
    date = models.DateField('feeding date')
    # B-reakfast
    # L-unch
    # D-inner
    meal = models.CharField(
        max_length=1,
        # add the custom 'choices' field option
        # this is what will create our dropdown menu
        choices=MEALS,
        # set the default choice, to be 'B'
        default=MEALS[0][0]
    )
    finch = models.ForeignKey(Finch, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.get_meal_display()} on {self.date} for {self.finch}"

    # change the default sort
    class Meta:
        ordering = ['-date']

main_app/forms.py
from django.forms import ModelForm
from .models import Feeding

class FeedingForm(ModelForm):
    class Meta:
        model = Feeding
        fields = ['date', 'meal']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from .models import Finch, Toy
from .forms import FeedingForm

# Create your testing finches here

#define home view
def home(request):
    return render(request, 'home.html')

#define about view
def about(request):
    return render(request, 'about.html')

#define finches index view 
def finches_index(request):
    finches = Finch.objects.all()
    return render(request, 'finches/index.html', {'finches': finches})

#define details view
def finches_detail(request, finch_id):
    finch = Finch.objects.get(id=finch_id)
    feeding_form = FeedingForm()
    return render(request, 'finches/detail.html', { 'finch': finch, 'feeding_form': feeding_form })

class FinchCreate(CreateView):
    model = Finch
    fields = '__all__'


class FinchUpdate(UpdateView):
    model = Finch
    # let's make it so you can't rename a cat
    # we could simply say fields = '__all__', or we can customize like this:
    fields = ['color', 'description', 'age']

# Delete View - extends DeleteView
class FinchDelete(DeleteView):
    model = Finch

    success_url = '/finches'

# this is to add a feeding
def add_feeding(request, finch_id):
    # create a ModelForm instance using the data in request.POST
    form = FeedingForm(request.POST)
    # it's also important to validate forms.
    # django gives us a built in function for that
    if form.is_valid():
        # dont want to save the feeding to the db until we have a finch id
        new_feeding = form.save(commit=False)
        # this is where we add the finch
        new_feeding.finch_id = finch_id
        new_feeding.save()
    #redirect
    return redirect('detail', finch_id=finch_id)

class ToyList(ListView):
    model = Toy
    template_name = 'toys/index.html'

# ToyDetail
class ToyDetail(DetailView):
    model = Toy
    template_name = 'toys/detail.html'

# ToyCreate
class ToyCreate(CreateView):
    model = Toy
    fields = ['name', 'color']

    def form_valid(self, form):
        return super().form_valid(form)

# ToyUpdate
class ToyUpdate(UpdateView):
    model = Toy
    fields = ['name', 'color']

# ToyDelete
class ToyDelete(DeleteView):
    model = Toy
    success_url = '/toys'

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

    <h1>About the Finch Collector</h1>
    <hr>
    <p>Hire the Finch Collector</p>

{% endblock %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>FinchCollector</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
    <header class="navbar-fixed">
        <nav>
            <div class="nav-wrapper">
                <ul>
                    <li>
                        <a href="/" class="left brand-logo">
                            &nbsp;&nbsp;Finch Collector
                        </a>
                    </li>
                </ul>
                <ul class="right">
                    <!-- <li><a href="/cats">Cats</a></li> -->
                    <li><a href="{% url 'index' %}">Finches</a></li>
                    <li><a href="{% url 'finches_create' %}">Add a Finch</a></li>
                    <!-- <li><a href="/about">About</a></li> -->
                    <li><a href="{% url 'about' %}">About</a></li>
                </ul>
            </div>
        </nav>
    </header>
    <main class="container">
        {% block content %}

        {% endblock %}
    </main>
</body>
</html>

main_app/templates/finches/detail.html
{% extends 'base.html' %}
{% block content %}

    <h1>{{ finch.name }}'s Details</h1>
    <div class="row">
        <div class="col s6">
            <div class="card">
                <div class="card-content">
                    <span class="card-title">{{ finch.name }}</span>
                    <p>Color: {{ finch.color }}</p>
                    <p>Description: {{ finch.description }}</p>
                    <p>Age: {{ finch.age }}</p>
                </div>
                <div class="card-action">
                    <a href="{% url 'finches_update' finch.id %}">Update</a>
                    <a href="{% url 'finches_delete' finch.id %}">Delete</a>
                </div>
            </div>
        </div>
        <div class="col s6">
            <form action="{% url 'add_feeding' finch.id %}" method="POST">
                {% csrf_token %}
                {{ feeding_form.as_p }}
                <input type="submit" class="btn" value="Add Feeding">
            </form>
            <hr>
            {% if finch.fed_for_today %}
                <div class="card-panel teal-text center-align">
                    {{finch.name}} has been fed all meals for today
                </div>
            {% else %}
                <div class="card-panel red-text center-align">
                    {{finch.name}} might be hungry
                </div>
            {% endif %}
            <hr>
            <table class="striped">
                <thead>
                    <tr><th>Date</th><th>Meal</th></tr>
                </thead>
                <tbody>
                    {% for feeding in finch.feeding_set.all %}
                        <tr>
                            <td>{{feeding.date}}</td>
                            <td>{{feeding.get_meal_display}}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div> 
    <script>
        // identify the element
        const dateEl = document.getElementById('id_date')
        // M is materialize's global variable
        M.Datepicker.init(dateEl, {
            format: 'yyyy-mm-dd',
            defaultDate: new Date(),
            setDefaultDate: true,
            autoClose: true
        })
        // here is where we'll render the dropdown (select)
        const selectEl = document.getElementById('id_meal')
        M.FormSelect.init(selectEl)
    </script>

{% endblock %}

main_app/templates/finches/index.html
{% extends 'base.html' %}

{% block content %}
    <!-- Your content goes here -->
    {% for finch in finches %}
        <div class="card">
            <a href="{% url 'detail' finch.id %}">
                <div class="card-content">
                    <span class="card-title">{{ finch.name }}</span>
                    <p>Color: {{ finch.color }}</p>
                    <p>Description: {{ finch.description }}</p>
                    <p>Age: {{ finch.age }}</p>
                </div>
                <!-- Close the div inside the loop -->
            </a>
        </div>
    {% endfor %}
{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}

{% block content %}
<h1>HOME</h1>
    <div class="image-container">
        <img src="https://i.imgur.com/h4t8W7N.jpeg" alt="Finch Image" width="300" height="200">
    </div>
{% endblock %}

{% block additional_styles %}
    <style>
        body {
            margin: 0;
            min-height: 100vh;
            display: flex;
            flex-direction: column;
            background: #fff; /* Set a background color */
        }

        .image-container {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 200px; /* Set to the desired height */
        }

        h1 {
            text-align: center;
            margin-top: 20px; /* Adjust the margin-top as needed */
        }

        footer.page-footer {
            margin-top: auto;
        }
    </style>
{% endblock %}

main_app/templates/main_app/finch_confirm_delete.html
{% extends 'base.html' %}
{% block content %}

    <h3>Delete Finch</h3>

    <h4>Are you sure you want to delete <span class="teal-text">{{ object.name}} </span>?</h4>

    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="Yes! - Delete" class="btn">
        <a href="{% url 'detail' cat.id %}" class="btn red">Cancel</a>
    </form>

{% endblock %}

main_app/templates/main_app/finch_form.html
{% extends 'base.html' %}
{% block content %}

    {% if object %}
        <h3>Edit {{ object.name }}</h3>
    {% else %}
        <h3>Add a Finch</h3>
    {% endif %}

    <form action="" method="POST">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit!" class="btn">
    </form>

{% endblock %}

main_app/templates/toys/detail.html
{% extends 'base.html' %}
{% block content %}
    <h1>Toy Details</h1>

    <div class="card">
        <div class="card-content">
            <span class="card-title">
                A <span style="color: {{ toy.color }}">{{toy.color}}</span> {{toy.name}}
            </span>
        </div>
        <div class="card-action">
            <a class="btn" href="{% url 'toys_update' toy.id %}">Edit</a>
            <a class="btn red" href="{% url 'toys_delete' toy.id %}">Delete</a>
        </div>
    </div>
{% endblock %}

main_app/templates/toys/index.html
{% extends 'base.html' %}
{% block content %}

    <h1>Toy List</h1>

    {% for toy in object_list %}
        <div class="card">
            <a href="{% url 'toys_detail' toy.id %}">
                <div class="card-content">
                    <span class="card-title">
                        A <span style="color: {{ toy.color }}">{{toy.color}}</span> {{toy.name}}
                    </span>
                </div>
            </a>
        </div>
    {% endfor %}

{% endblock %}